### ISSUE TITLE
Prog6Tests Union Passes Set []

### ISSUE THREAD

**Issue by gregprojects** [zrp942382/CSC345#5]
Hey Zack,
In your Prog6Tests union test, you call union (Set []) (Set [1]) and union (Set [1]) (Set []) on lines 64 and 66. I thought that Set [] would never be tested on per the piazza response: "For the Sets: I will always pass in EmptySet and never Set []".

**Comment by zrp942382** [comment]
Oh wow, someone finally opened an issue! I'm aware, it's meant to be in there. I must have either missed a comment or two in some of the code, explaining why the test is in there, or I had meant to comment it out as an "extra" test.
